import express from 'express';
import request from 'supertest';
import authRoutes from '../auth.route';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcrypt';

// Create a standalone app for testing the route logic
const app = express();
app.use(express.json());
app.use('/api/auth', authRoutes);

// Mock the DB module
jest.mock('../../../core/db', () => {
  return {
    __esModule: true,
    default: {
      query: jest.fn(),
      pool: {
        connect: jest.fn().mockResolvedValue({
          query: jest.fn(),
          release: jest.fn(),
        }),
      },
    },
  };
});

// Import the mocked DB
import db from '../../../core/db';

describe('Auth APIs', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('POST /api/auth/register-customer', () => {
    it('should return 400 if fields are missing', async () => {
      const res = await request(app).post('/api/auth/register-customer').send({
        email: 'test@example.com'
        // missing name, password
      });
      expect(res.status).toBe(400);
      expect(res.body.success).toBe(false);
    });

    it('should return 201 when registered successfully and hash password', async () => {
      // Mock db insertion
      (db.query as jest.Mock).mockResolvedValueOnce({
        rows: [{ id: 'some-uuid', email: 'test@example.com', role: 'customer', status: 'active' }]
      });

      const res = await request(app).post('/api/auth/register-customer').send({
        name: 'Test Customer',
        email: 'test@example.com',
        password: 'securePassword123'
      });

      expect(res.status).toBe(201);
      expect(res.body.success).toBe(true);
      expect(res.body.data.role).toBe('customer');

      // Verify bcrypt was used with 12 salt rounds (implicitly, we can check the calls to the DB mock)
      expect(db.query).toHaveBeenCalledTimes(1);
      const queryValues = (db.query as jest.Mock).mock.calls[0][1];
      const insertedPasswordHash = queryValues[2];
      
      // The hash should be genuinely generated by bcrypt during controller execution
      const isMatch = await bcrypt.compare('securePassword123', insertedPasswordHash);
      expect(isMatch).toBe(true);
    });

    it('should return 409 if email is already taken', async () => {
      (db.query as jest.Mock).mockRejectedValueOnce({ code: '23505' }); // Unique violation

      const res = await request(app).post('/api/auth/register-customer').send({
        name: 'Test',
        email: 'taken@example.com',
        password: 'password'
      });

      expect(res.status).toBe(409);
      expect(res.body.success).toBe(false);
      expect(res.body.message).toMatch(/Email is already taken/i);
    });
  });

  describe('POST /api/auth/login', () => {
    it('should return 401 if credentials are wrong', async () => {
      (db.query as jest.Mock).mockResolvedValueOnce({ rows: [] }); // User not found

      const res = await request(app).post('/api/auth/login').send({
        email: 'notfound@example.com',
        password: 'wrongpassword'
      });

      expect(res.status).toBe(401);
      expect(res.body.success).toBe(false);
    });

    it('should return 403 if account is banned', async () => {
      (db.query as jest.Mock).mockResolvedValueOnce({ 
        rows: [{ id: '1', email: 'banned@example.com', password_hash: 'hash', status: 'banned' }] 
      });

      const res = await request(app).post('/api/auth/login').send({
        email: 'banned@example.com',
        password: 'any'
      });

      expect(res.status).toBe(403);
      expect(res.body.message).toMatch(/banned/i);
    });

    it('should return 200 and a JWT token with correct payload on success', async () => {
      const passwordHash = await bcrypt.hash('correctPassword', 12);
      
      (db.query as jest.Mock).mockResolvedValueOnce({ 
        rows: [{ id: 'some-uuid', name: 'Vendor User', email: 'vendor@example.com', password_hash: passwordHash, role: 'vendor', status: 'active' }] 
      });
      // Mock the second query finding the vendor id
      (db.query as jest.Mock).mockResolvedValueOnce({
        rows: [{ id: 'vendor-uuid' }]
      });

      const res = await request(app).post('/api/auth/login').send({
        email: 'vendor@example.com',
        password: 'correctPassword'
      });

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(res.body.data.token).toBeDefined();

      // Verify Token Content Structure as per Rule
      const decoded = jwt.decode(res.body.data.token) as any;
      expect(decoded.id).toBe('some-uuid');
      expect(decoded.role).toBe('vendor');
      expect(decoded.vendor_id).toBe('vendor-uuid');
    });
  });
});
